---
- name: Converge
  hosts: all
  tasks:
    - name: "Include vdo.age_backup"
      ansible.builtin.include_role:
        name: vdo.age_backup
      vars:
        remote_backup_paths:
          - "/var/log/"
        local_backup_destination: "~"
        github_users:
          - "vdo"
