---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  log: false
verifier:
  name: ansible
scenario:
  test_sequence:
      - dependency
      - cleanup
      - destroy
      - create
      - prepare
      - converge
      - verify
      - cleanup
      - destroy
