---
- name: Verify
  hosts: all
  tasks:
    - name: List generated backups
      ansible.builtin.shell: "ls -l ~/*.age"
      delegate_to: localhost
      register: ls

    - debug:
        msg: "{{ ls.stdout }}"