---
name: Check Molecule

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1
  ANSIBLE_FORCE_COLOR: 1

jobs:
  molecule-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
        env:
          ANSIBLE_FORCE_COLOR: "1"
